import type { Abstract } from './utility';

export type LogoType = Abstract<number, 'LogoType'>;

/**
 * Enumeration of logo types.
 */
export const LogoType = {
  Unknown: 0 as LogoType,
  DF: 1 as LogoType,
  DFARES: 2 as LogoType,
  DFArchon: 3 as LogoType,
  AltLayer: 4 as LogoType,
  AGLDDAO: 5 as LogoType,
  Mask: 6 as LogoType,
  Web3MQ: 7 as LogoType,
  DeGame: 8 as LogoType,
  FunBlocks: 9 as LogoType,
  GamePhylum: 10 as LogoType,
  MarrowDAO: 11 as LogoType,
  OrdenGG: 12 as LogoType,
  DFDAO: 13 as LogoType,
  Two77DAO: 14 as LogoType,
  Zero1a1: 15 as LogoType,
  WeirdaoGhostGang: 16 as LogoType,
  Briq: 17 as LogoType,
  SeeDAO: 18 as LogoType,
  NetherScape: 19 as LogoType,
  TownStoryGalaxy: 20 as LogoType,
  BlockBeats: 21 as LogoType,
  Cointime: 22 as LogoType,
  ChainCatcher: 23 as LogoType,
  ForesightNews: 24 as LogoType,
  DAppChaser: 25 as LogoType,
  MatrixWorld: 26 as LogoType,
  AWHouse: 27 as LogoType,
  PaladinsDAO: 28 as LogoType,
  UpchainDAO: 29 as LogoType,
  LXDAO: 30 as LogoType,
  CryptoChasers: 31 as LogoType,
  AWResearch: 32 as LogoType,
  BlockPi: 33 as LogoType,
  WhalerDAO: 34 as LogoType,
  Gametaverse: 35 as LogoType,
  BuidlerDAO: 36 as LogoType,
  THUBA: 37 as LogoType,
  NJUBA: 38 as LogoType,
  RUChain: 39 as LogoType,
  SIEA: 40 as LogoType,
  PTADAO: 41 as LogoType,
  ZJUBCA: 42 as LogoType,
  Cellula: 43 as LogoType,
  WTFAcademy: 44 as LogoType,
  DappLearning: 45 as LogoType,
  FFGDAO: 46 as LogoType,
  Rooch: 47 as LogoType,
  ggQuest: 48 as LogoType,
  CryptoChasersRobot: 49 as LogoType,
  // Don't forget to update MIN_LOGO_TYPE and/or MAX_LOGO_TYPE in the `constants` package
};

/**
 * Mapping from LogoType to pretty-printed names.
 */
export const LogoTypeNames = {
  [LogoType.Unknown]: 'Unknown',
  [LogoType.DF]: 'Dark Forest',
  [LogoType.DFARES]: 'DF ARES',
  [LogoType.DFArchon]: 'DF Archon',
  [LogoType.AltLayer]: 'AltLayer',
  [LogoType.AGLDDAO]: 'AGLD DAO',
  [LogoType.Mask]: 'Mask Network',
  [LogoType.Web3MQ]: 'Web3MQ',
  [LogoType.DeGame]: 'DeGame',
  [LogoType.FunBlocks]: 'Fun Blocks',
  [LogoType.GamePhylum]: 'GamePhylum',
  [LogoType.MarrowDAO]: 'MarrowDAO | Guild W',
  [LogoType.OrdenGG]: 'Orden GG',
  [LogoType.DFDAO]: 'DFDAO',
  [LogoType.Two77DAO]: '277 DAO',
  [LogoType.Zero1a1]: '01a1',
  [LogoType.WeirdaoGhostGang]: 'Weirdao Ghost Gang',
  [LogoType.Briq]: 'Briq',
  [LogoType.SeeDAO]: 'SeeDAO',
  [LogoType.NetherScape]: 'NetherScape',
  [LogoType.TownStoryGalaxy]: 'TownStory Galaxy',
  [LogoType.BlockBeats]: 'BlockBeats',
  [LogoType.Cointime]: 'Cointime',
  [LogoType.ChainCatcher]: 'ChainCatcher',
  [LogoType.ForesightNews]: 'ForesightNews',
  [LogoType.DAppChaser]: 'DAppChaser',
  [LogoType.MatrixWorld]: 'Matrix World',
  [LogoType.AWHouse]: 'AWHouse',
  [LogoType.PaladinsDAO]: 'PaladinsDAO',
  [LogoType.UpchainDAO]: 'UpchainDAO',
  [LogoType.LXDAO]: 'LXDAO',
  [LogoType.CryptoChasers]: 'Crypto Chasers',
  [LogoType.AWResearch]: 'AW Research',
  [LogoType.BlockPi]: 'BlockPi',
  [LogoType.WhalerDAO]: 'WhalerDAO',
  [LogoType.Gametaverse]: 'Gametaverse',
  [LogoType.BuidlerDAO]: 'BuidlerDAO',
  [LogoType.THUBA]: 'THUBA',
  [LogoType.NJUBA]: 'NJUBA',
  [LogoType.RUChain]: 'RUChain',
  [LogoType.SIEA]: 'SIEA',
  [LogoType.PTADAO]: 'PTADAO',
  [LogoType.ZJUBCA]: 'ZJUBCA',
  [LogoType.Cellula]: 'Cellula',
  [LogoType.WTFAcademy]: 'WTF Academy',
  [LogoType.DappLearning]: 'Dapp Learning',
  [LogoType.FFGDAO]: 'FFG DAO',
  [LogoType.Rooch]: 'Rooch',
  [LogoType.ggQuest]: 'ggQuest',
  [LogoType.CryptoChasersRobot]: 'CryptoChasers Robot',
} as const;
